### ISSUE TITLE
Latest Quiz feature list for August 15th deadline

### ISSUE THREAD

**Issue by tclzcja** [the-core-studio/vox-issue#117]
- [x] MCQ, SAQ design and player function.
- [x] Grading function (for SAQ at the moment).
- [x] Report function so the student can see final result.
- [x] Explanation.
- [x] Time limit.
- [x] Navigation component like floating scrollbar and dots progress bar.

**Comment by botelho-852** [comment]
TBL pedagogy -  quiz 1 and quiz 2 - the first is done by all students the second is done by the group 
two step process - quiz 1 - no score results or score but not knowing which questions are right or wrong. knowing which questions are right and wrong and finally knowing which questions are R or Wrong AND explanation.

**Comment by botelho-852** [comment]
Quiz task design by teacher - **open access or study mode** = quiz/questions students can answer any time multiple - the question they get wrong they repeat - needs a reminder to repeat in the future like a flashcard library to repeat . ideally there would be a reminder.

**Comment by botelho-852** [comment]
**Teacher quiz task design** by teacher or RA 
1) Time limit - fixed summative 2-3pm set. if you turn up late you loose time. 
2) flexible - planned to start at 2-3 pm ... sorry we are 5 mins late it is 2.05-3.05 
flexible to add more time to push back. 
3) when you start you have 60 mins - study mode?

**Comment by botelho-852** [comment]
import function questions from Moodle. - there is an export function in Moodle.

**Comment by tclzcja** [comment]
Done. I'll transfer your comments to individual issues. @botelho-852
