### ISSUE TITLE
Question-group/chain/connected Questions

### ISSUE THREAD

**Issue by tclzcja** [the-core-studio/vox-issue#118]
1 - 2 - 3.

**Comment by botelho-852** [comment]
forward navigation only up to X questions...

**Comment by botelho-852** [comment]
**NEXT forward navigation only SAQ and MCQ** 
Later .... for noting... how students mark SAQ.... they need an answer rubric

**Comment by tclzcja** [comment]
Working for vertical layout now.

**Comment by tclzcja** [comment]
This is done.
