### ISSUE TITLE
Course duplication from year to year with new cohort. ... what happens to comments and analytics. 

### ISSUE THREAD

**Issue by botelho-852** [the-core-studio/vox-issue#158]
Ideally when you duplicate a course from one year to the next you do not want to keep analytics. and probably NOT comments. 

Out of the two comments will be more useful to keep ideally by hiding and may be later exposing on demand from the teacher. 

Or keep the comments and let them accumulate.. from year to year. 

If you do archive then you wnat a filtering system at the top to chose the year or course batch

thanks
M

**Comment by tclzcja** [comment]
A basic group filter has been added to the comments area. Further changes will be applied to enhance this filter, like archiving function for Groups.

**Comment by tclzcja** [comment]
Group archive and Comment filter are both implemented, this should solve most of the Course duplication scenario. Closing this.
